services:
  media-browser:
    build: .
    restart: unless-stopped
    volumes:
      - ./media:/media:ro
    environment:
      MEDIA_DIR: /media
      PORT: 8080
      BASE_PATH: /qwerty/
    ports:
      - 8080:8080
